aws-auth: &aws-auth
  aws_auth:
    aws_access_key_id: $ECR_AWS_ACCESS_KEY_ID
    aws_secret_access_key: $ECR_AWS_SECRET_ACCESS_KEY

version: 2.1
jobs:
  lint:
    docker:
      - image: $SALSIFY_ECR_REPO/ruby_ci:2.7.7
        <<: *aws-auth
    working_directory: ~/delayed_job_groups
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gems-ruby-2.7.7-{{ checksum "delayed_job_groups.gemspec" }}-{{ checksum "Gemfile" }}
            - v1-gems-ruby-2.7.7-
      - run:
          name: Install Gems
          command: |
            if ! bundle check --path=vendor/bundle; then
              bundle install --path=vendor/bundle --jobs=4 --retry=3
              bundle clean
            fi
      - save_cache:
          key: v1-gems-ruby-2.7.7-{{ checksum "delayed_job_groups.gemspec" }}-{{ checksum "Gemfile" }}
          paths:
            - "vendor/bundle"
            - "gemfiles/vendor/bundle"
      - run:
          name: Run Rubocop
          command: bundle exec rubocop
  test:
    parameters:
      gemfile:
        type: string
      ruby_version:
        type: string
    docker:
      - image: $SALSIFY_ECR_REPO/ruby_ci:<< parameters.ruby_version >>
        <<: *aws-auth
    environment:
      CIRCLE_TEST_REPORTS: "test-results"
      BUNDLE_GEMFILE: << parameters.gemfile >>
    working_directory: ~/delayed_job_groups
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gems-ruby-<< parameters.ruby_version >>-{{ checksum "delayed_job_groups.gemspec" }}-{{ checksum "<< parameters.gemfile >>" }}
            - v1-gems-ruby-<< parameters.ruby_version >>-
      - run:
          name: Install Gems
          command: |
            if ! bundle check --path=vendor/bundle; then
              bundle install --path=vendor/bundle --jobs=4 --retry=3
              bundle clean
            fi
      - save_cache:
          key: v1-gems-ruby-<< parameters.ruby_version >>-{{ checksum "delayed_job_groups.gemspec" }}-{{ checksum "<< parameters.gemfile >>" }}
          paths:
            - "vendor/bundle"
            - "gemfiles/vendor/bundle"
      - run:
          name: Run Tests
          command: |
            bundle exec rspec --format RspecJunitFormatter --out $CIRCLE_TEST_REPORTS/rspec/junit.xml --format progress spec
      - store_test_results:
          path: "test-results"
workflows:
  build:
    jobs:
      - lint:
          context: Salsify
      - test:
          context: Salsify
          matrix:
            parameters:
              gemfile:
                - "gemfiles/rails_6.0.gemfile"
                - "gemfiles/rails_6.1.gemfile"
                - "gemfiles/rails_7.0.gemfile"
              ruby_version:
                - "2.7.7"
                - "3.0.5"
                - "3.1.3"
                - "3.2.0"
